from __future__ import annotations

from typing import Any, Protocol


class SkillProvider(Protocol):
    def manifest(self, skill_ids: list[str]) -> list[dict[str, Any]]: ...

    def skill_prompt_entries(
        self, skill_ids: list[str], *, max_chars: int = 20000
    ) -> list[dict[str, Any]]: ...

    def read_only_mounts(self, skill_ids: list[str]) -> list[tuple[str, str]]: ...

    def list_skills(self) -> list[dict[str, Any]]: ...

    def describe_skill(self, skill_id: str) -> dict[str, Any]: ...

    def install_skill(self, skill_id: str, files: dict[str, bytes]) -> dict[str, Any]: ...

    def install_zip(self, skill_id: str, payload: bytes) -> dict[str, Any]: ...

    def remove_skill(self, skill_id: str) -> bool: ...
